author:                                     #自定义常亮
  name: 王健杰
  email: wangjianjie606@gmail.com
baseurl: /dono
safe: false
excerpt_separator: "\n\n\n"
pic_url: "https://raw.githubusercontent.com/wangjianjie606/dono/gh-pages/images/"