author:                                     #自定义常亮
  name: 王健杰
  email: wangjianjie606@gmail.com
  site: https://wangjianjie606.github.io/dono/
baseurl: /dono
safe: false
excerpt_separator: "\n\n"
pic_url: "https://raw.githubusercontent.com/wangjianjie606/dono/gh-pages/images"
encoding: "utf-8"
